'use client';
import {useEffect,useState} from 'react';
import Image from 'next/image';
import type {Profile} from '@/lib/types';

const sites=[['wsop','WSOP'],['mspt','MSPT'],['hendon','The Hendon Mob'],['sharkscope','Sharkscope']] as const;
export default function ProfilePanel({id,me,onChanged}:{id:string;me:string;onChanged?:()=>void}){
 const [profile,setProfile]=useState<Profile|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState(false);
 const [draft,setDraft]=useState({name:'',bio:'',photo:'',wsop:'',mspt:'',hendon:'',sharkscope:''});
 async function load(){const response=await fetch('/api/social?id='+encodeURIComponent(id));const json=await response.json();if(!response.ok)throw Error(json.error||'Could not load profile.');setProfile(json.profile);setDraft(json.profile);}
 useEffect(()=>{let active=true;fetch('/api/social?id='+encodeURIComponent(id)).then(async response=>{const json=await response.json();if(!response.ok)throw Error(json.error||'Could not load profile.');if(active){setProfile(json.profile);setDraft(json.profile)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[id]);
 async function action(type:string){setBusy(true);setError('');try{const response=await fetch('/api/social',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:type,id,...(type==='profile'?draft:{})})});const json=await response.json();if(!response.ok)throw Error(json.error||'Could not save.');await load();setEdit(false);onChanged?.()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function photo(file:File){setError('');if(!/^image\/(jpeg|png|webp|heic|heif)$/.test(file.type)||file.size>5_000_000){setError('Use a photo under 5 MB.');return}try{const image=await createImageBitmap(file);const canvas=document.createElement('canvas');const size=240;canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d');if(!ctx)throw Error('Photo processing is unavailable.');const crop=Math.min(image.width,image.height);ctx.drawImage(image,(image.width-crop)/2,(image.height-crop)/2,crop,crop,0,0,size,size);image.close();const value=canvas.toDataURL('image/jpeg',.72);if(value.length>220000)throw Error('Photo is still too large; choose a smaller one.');setDraft(d=>({...d,photo:value}));}catch{setError('Your browser could not open this photo. Try a JPG or PNG instead.')}}
 if(error&&!profile)return <p className="error" role="alert">{error}</p>;
 if(!profile)return <p className="muted">Loading player profile…</p>;
 return <div className="post-form profile-panel">{error&&<p className="error" role="alert">{error}</p>}
  <div className="profile-overview">{profile.photo?<Image src={profile.photo} alt="" width={76} height={76} unoptimized className="profile-photo"/>:<span className="profile-photo profile-initial">{profile.name.slice(0,1)}</span>}<div><h3>{profile.name}</h3><span>{profile.followers} followers · {profile.following} following</span></div></div>
  {edit&&id===me?<><label className="field">Display name<input value={draft.name} maxLength={60} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="field">Bio<textarea value={draft.bio} maxLength={500} rows={3} onChange={e=>setDraft({...draft,bio:e.target.value})}/></label><label className="field">Profile photo<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void photo(f)}}/></label>{draft.photo&&<button type="button" className="outline" onClick={()=>setDraft({...draft,photo:''})}>Remove photo</button>}{sites.map(([key,label])=><label className="field" key={key}>{label} profile link<input type="url" placeholder="https://" value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<button className="primary" disabled={busy} onClick={()=>void action('profile')}>Save profile</button><button className="outline" onClick={()=>setEdit(false)}>Cancel</button></>:<><p className="muted">{profile.bio||'No bio yet.'}</p><div className="profile-links">{sites.map(([key,label])=>profile[key]&&<a key={key} href={profile[key]} target="_blank" rel="noopener noreferrer" className="outline">{label} ↗</a>)}</div>{id===me?<button className="outline" onClick={()=>setEdit(true)}>Edit my profile</button>:<div className="profile-controls"><button className="primary" disabled={busy||profile.isBlocked} onClick={()=>void action(profile.isFollowing?'unfollow':'follow')}>{profile.isFollowing?'Unfollow':'Follow'}</button><button className="outline" disabled={busy} onClick={()=>void action(profile.isBlocked?'unblock':'block')}>{profile.isBlocked?'Unblock player':'Block player'}</button></div>}{profile.isBlocked&&<p className="form-hint">You have blocked this player. Their posts and comments are hidden from your view, and neither of you can follow the other.</p>}</>}
 </div>
}
