'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Spade,Users,Plus,ArrowUpRight,Lock,MessageCircle,Heart,Flag,ChevronDown,ArrowLeft,Copy,Check,Radio,Layers3,LogOut,RefreshCw,Send,Trash2,Eye,ChartNoAxesCombined,Flame,BookOpen,X} from 'lucide-react';
import type {Group,Post,User,Hand,Tournament} from '@/lib/types';
import {connectSpotSolver,solverHand,SOLVER_URL, type ImportState} from '@/lib/spot-solver';
import {postSchema} from '@/lib/validation';

function Avatar({name,small=false}:{name:string;small?:boolean}){const letters=name.split(' ').slice(0,2).map(s=>s[0]).join('');return <span className={'avatar '+(small?'small':'')} style={{'--avatar-hue':String((name.charCodeAt(0)*13)%360)} as React.CSSProperties}>{letters}</span>}
function Cards({cards}:{cards:string}){return <span className="playing-cards">{cards.trim().split(/\s+/).filter(Boolean).map((card,i)=><span key={i} className={'playing-card '+(/[hd]$/i.test(card)?'red':'')}><b>{card[0]?.toUpperCase()}</b><span>{{h:'♥',d:'♦',c:'♣',s:'♠'}[card[1]?.toLowerCase()]}</span></span>)}</span>}
function Modal({title,description,children,onClose,wide=false}:{title:string;description?:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[]);return <dialog ref={ref} className="modal" style={wide?{width:"min(1200px, 96vw)",maxWidth:"96vw"}:undefined} aria-labelledby="modal-title" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><div className="modal-head"><div><h2 id="modal-title">{title}</h2>{description&&<p>{description}</p>}</div><button type="button" className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={21}/></button></div>{children}</dialog>}
function Field({label,name,placeholder,required=false,defaultValue='',type='text'}:{label:string;name:string;placeholder?:string;required?:boolean;defaultValue?:string;type?:string}){return <label className="field">{label}<input name={name} placeholder={placeholder} required={required} defaultValue={defaultValue} type={type} min={type==='number'?0:undefined} maxLength={200}/></label>}

function SpotSolverPanel({post}:{post:Post|null}){
 const frame=useRef<HTMLIFrameElement>(null);
 const bridge=useRef<ReturnType<typeof connectSpotSolver>|null>(null);
 const [status,setStatus]=useState<{state:ImportState;message:string}|null>(null);
 useEffect(()=>{
  if(!frame.current)return;
  const connection=connectSpotSolver(frame.current,(state,message)=>setStatus({state,message}));
  bridge.current=connection;
  if(post?.hand)connection.importHand(solverHand(post));
  else setStatus(null);
  return()=>{connection.destroy();bridge.current=null;};
 },[post]);
 return <div className="post-form"><h3>{post?'Analyze this hand in Spot Solver':'Study with Spot Solver'}</h3>
 {status&&<p role="status" aria-live="polite" className={status.state==='rejected'||status.state==='timeout'?'error':'muted'}>{status.message}</p>}
 {post&&<><p className="form-hint">Cards, position, and notes transfer into the analyzer. Original amounts stay in notes: review units, players, pot, amount to call, and ranges. Importing does not run a calculation.</p><button className="outline" disabled={status?.state==='pending'} onClick={()=>bridge.current?.importHand(solverHand(post))}>{status?.state==='imported'?'Reimport original hand':'Retry import'}</button></>}
 <iframe ref={frame} src={SOLVER_URL} title="Spot Solver poker study tools" referrerPolicy="no-referrer" style={{width:'100%',height:'72dvh',minHeight:480,border:'1px solid #394332',borderRadius:12,background:'#050c09'}}/>
 <a className="outline" href={SOLVER_URL} target="_blank" rel="noopener noreferrer">Open Spot Solver separately <ArrowUpRight size={16}/></a><p className="form-hint">Hand import works in this panel, not the separate tab. Spot Solver accounts are separate from RailSupport.</p></div>;
}

const newHand:Hand={game:'NL Hold’em',stakes:'',position:'BTN',stack:'',hero:'',board:'',pot:'',action:'',question:'',result:'',revealed:false};

export default function RailApp({ready}:{ready:boolean}){
 const [user,setUser]=useState<User>({id:'',name:''}),[signedOut,setSignedOut]=useState(true),[groups,setGroups]=useState<Group[]>([]),[posts,setPosts]=useState<Post[]>([]),[active,setActive]=useState(''),[members,setMembers]=useState<User[]>([]),[tab,setTab]=useState('all'),[view,setView]=useState('feed');
 const [modal,setModal]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[expanded,setExpanded]=useState<string[]>([]),[copied,setCopied]=useState(false),[authMode,setAuthMode]=useState('signup');
 const [body,setBody]=useState(''),[hand,setHand]=useState<Hand>(newHand),[updateKind,setUpdateKind]=useState('text'),[postKind,setPostKind]=useState<'update'|'hand'>('update');
 const [checking,setChecking]=useState(ready);
 const [solverPost,setSolverPost]=useState<Post|null>(null);
 function openSolver(post:Post|null=null){setSolverPost(post);setCopied(false);open('solver');}
 const activeRef=useRef(active);activeRef.current=active;
 const current=groups.find(g=>g.id===active);
 const filtered=posts.filter(p=>p.groupId===active&&(tab==='all'||p.kind===tab));
 const latest=posts.find(p=>p.groupId===active&&p.tournament)?.tournament;
 async function api(path:string,values?:Record<string,unknown>){const res=await fetch(path,values?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)}:undefined);const data=await res.json();if(!res.ok)throw Error(data.error||data.message||'Something went wrong. Please try again.');return data;}
 const loadGroup=useCallback(async(id:string)=>{if(!id)return;const data=await api('/api/rail?group='+encodeURIComponent(id));if(activeRef.current===id){setPosts(data.posts);setMembers(data.members);}},[]);
 async function loadAccount(select?:string){const data=await api('/api/rail');setUser(data.user);setGroups(data.groups);setSignedOut(false);setPosts([]);setActive(select||data.groups[0]?.id||'');}
 useEffect(()=>{if(!ready)return;fetch('/api/rail').then(async r=>{if(r.status===401)return;if(!r.ok)throw Error('Could not reconnect. Your saved posts have not been changed.');const d=await r.json();setUser(d.user);setGroups(d.groups);setSignedOut(false);setPosts([]);setActive(d.groups[0]?.id||'')}).catch(e=>setError(e.message)).finally(()=>setChecking(false));},[ready]);
 useEffect(()=>{if(signedOut||!active)return;setLoading(true);loadGroup(active).catch(e=>setError(e.message)).finally(()=>setLoading(false));const timer=setInterval(()=>loadGroup(active).catch(()=>{}),20000);return()=>clearInterval(timer);},[signedOut,active,loadGroup]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(timer)},[notice]);
 function open(kind:string){setError('');setModal(kind);}
 async function mutate(action:string,data:Record<string,unknown>={}){
  if(busy)return false;setBusy(true);setError('');try{
   if(signedOut)throw Error('Sign in before posting.');
   const res=await api('/api/rail',{action,...data});if(action==='create'||action==='join')await loadAccount(res.id);else await loadGroup(active);
   return true;
  }catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}
 }
 async function authenticate(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!ready)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await api('/api/auth/'+(authMode==='signup'?'sign-up/email':'sign-in/email'),{name:f.get('name'),email:f.get('email'),password:f.get('password')});await loadAccount();setModal('');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function submitPost(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);let tournament:Tournament|undefined;if(postKind==='update'&&updateKind==='tournament')tournament={event:String(f.get('event')),chips:Number(f.get('chips')),bigBlind:Number(f.get('bigBlind')),remaining:Number(f.get('remaining')),status:f.get('status') as Tournament['status']};const data={groupId:active,kind:postKind,body,hand:postKind==='hand'?hand:undefined,tournament};const parsed=postSchema.safeParse(data);if(!parsed.success){setError(parsed.error.issues[0].message);return}if(await mutate('post',parsed.data)){setBody('');setHand(newHand);setModal('');setTab('all');}}
 function compose(kind:'update'|'hand'){if(!current){open('create');return}setPostKind(kind);open('compose');}
 if(signedOut)return <div className="app-shell"><div className="stage-background" aria-hidden="true"/><main style={{maxWidth:480,margin:'0 auto',padding:'64px 20px'}}><section className="panel" style={{padding:28}}><div className="eyebrow"><Spade size={24}/> RAILSUPPORT</div><h1>Your people. Your poker.</h1><p className="muted">Create your account, start a private rail, and invite your friends.</p>{error&&<p className="error" role="alert">{error}</p>}{checking?<p role="status">Checking your account…</p>:ready?<form className="post-form" onSubmit={authenticate}><p className="muted">Your own RailSupport account. No ChatGPT required.</p><div className="compose-toggle"><button type="button" className={authMode==='signup'?'selected':''} onClick={()=>setAuthMode('signup')}>Create account</button><button type="button" className={authMode==='signin'?'selected':''} onClick={()=>setAuthMode('signin')}>Sign in</button></div>{authMode==='signup'&&<Field name="name" label="Display name" required/>}<Field name="email" label="Email" type="email" required/><label className="field">Password<input name="password" type="password" minLength={8} maxLength={128} required autoComplete={authMode==='signup'?'new-password':'current-password'}/></label><p className="form-hint">Use at least 8 characters. Email verification and self-service password recovery are not enabled in this pilot.</p><button className="primary" disabled={busy}>{busy?'Please wait…':authMode==='signup'?'Create account':'Sign in'}</button></form>:<p role="status">Account setup is being completed. Please check back shortly.</p>}</section></main></div>;
 return <div className="app-shell"><div className="stage-background" aria-hidden="true"/><header className="topbar"><a href="/" className="brand"><span className="brand-mark"><Spade size={23} fill="currentColor"/></span><span>RAIL<span className="gold">SUPPORT</span></span><span className="beta">V1.2</span></a><nav className="topnav" aria-label="Main navigation"><button className={view==='feed'?'active':''} onClick={()=>setView('feed')}>My rail</button><button className={view==='groups'?'active':''} onClick={()=>setView('groups')}>My groups</button><button onClick={()=>openSolver()}>Study tools</button></nav><button className="account" onClick={()=>open('account')}><Avatar name={user.name} small/><span>{signedOut?'Preview player':user.name}</span><ChevronDown size={14}/></button></header>

 <div className="layout"><aside className="left-sidebar"><div className="sidebar-caption">YOUR INNER CIRCLE</div><h2>Your people.<br/><em>Your poker.</em></h2><div className="sidebar-separator"/><div className="section-heading"><span>MY PRIVATE RAILS</span><span>{groups.length.toString().padStart(2,'0')}</span></div><div className="rail-list">{groups.map((g,i)=><button key={g.id} disabled={busy} className={'rail-link '+(g.id===active?'selected':'')} onClick={()=>{setActive(g.id);setView('feed');setTab('all');setError('')}}><span className={'rail-icon tone-'+i%3}>{g.kind==='Study group'?<Spade size={19}/>:g.kind==='Backers'?<Layers3 size={19}/>:<Users size={19}/>}</span><span>{g.name}<small>{g.kind}</small></span>{g.id===active&&<span className="selection-mark"/>}</button>)}</div><button className="sidebar-action" onClick={()=>open('create')}><Plus size={17}/> Create a private rail</button><button className="sidebar-action" onClick={()=>open('join')}><ArrowUpRight size={17}/> Join with an invite</button><div className="privacy-note"><Lock size={17}/><div>Invite only. Always.<p>Every rail has its own members and its own conversations.</p></div></div><div className="sidebar-footer">A BUZ TRIO PROJECT <span>♠</span></div></aside>
 <main className="main-content">{error&&!modal&&<div className="error" role="alert">{error}</div>}
 {view==='groups'?<><div className="page-title"><div><span className="eyebrow">A SEAT FOR YOUR PEOPLE</span><h1>My private rails</h1></div><button className="primary" onClick={()=>open('create')}><Plus size={17}/> New rail</button></div><div className="group-grid">{groups.map(g=><button className="group-card panel" key={g.id} onClick={()=>{setActive(g.id);setView('feed')}}><Users size={26}/><span className="eyebrow">{g.kind}</span><h2>{g.name}</h2><p>{g.description}</p><span>{g.members} members <ArrowUpRight size={16}/></span></button>)}</div></>:<>
 <div className="page-title"><div><span className="eyebrow"><Lock size={12}/> YOUR PRIVATE RAIL</span><h1>{current?.name||'Make your first rail.'}</h1><p>{current?.description||'Bring your friends, study partners, or backers together.'}</p></div>{current&&<button className="outline" onClick={()=>open('invite')}><Users size={16}/> Invite friends</button>}</div>
 {!current?<section className="empty panel"><Spade size={36}/><h2>Every player needs a rail.</h2><p>Create a private space for the people in your corner.</p><button className="primary" onClick={()=>open('create')}><Plus size={17}/> Create my rail</button></section>:<>
 <section className="composer panel"><div className="composer-prompt"><Avatar name={user.name}/><button onClick={()=>compose('update')}>What’s happening on your side of the felt?</button></div><div className="composer-actions"><button onClick={()=>{setUpdateKind('tournament');compose('update')}}><Flag size={17}/><span>Tournament update</span></button><button onClick={()=>compose('hand')}><Spade size={17}/><span>Discuss a hand</span></button><button className="share-button" onClick={()=>{setUpdateKind('text');compose('update')}}>New post <Plus size={16}/></button></div></section>
 <div className="feed-tabs" role="tablist" aria-label="Post type">{[['all','All activity'],['update','Rail updates'],['hand','Hand discussions']].map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}<button className="refresh icon-button" aria-label="Refresh activity" onClick={()=>{if(signedOut)setNotice('You’re viewing sample activity.');else loadGroup(active).catch(e=>setError(e.message))}}><RefreshCw size={15}/></button></div>
 {loading?<div className="panel empty"><RefreshCw className="spin"/><p>Loading your rail…</p></div>:filtered.length===0?<div className="panel empty"><MessageCircle size={30}/><h2>Start the conversation.</h2><p>Share an update or a hand you’ve finished playing.</p><button className="outline" onClick={()=>compose('update')}>Write the first post</button></div>:filtered.map(p=><article className="post panel" key={p.id}><div className="post-head"><Avatar name={p.name}/><div><strong>{p.name}</strong><div className="post-meta">{signedOut?'Sample activity':new Date(p.created).toLocaleDateString(undefined,{month:'short',day:'numeric'})}<span>·</span><Lock size={10}/>{current.name}</div></div><span className={'post-kind '+p.kind}>{p.kind==='hand'?<><Spade size={12}/> HAND DISCUSSION</>:<><Flag size={12}/> RAIL UPDATE</>}</span>{p.userId===user.id&&<button className="icon-button delete-post" aria-label="Delete post" onClick={()=>open('delete:'+p.id)}><Trash2 size={14}/></button>}</div>
 {p.body&&<p className="post-body">{p.body}</p>}
 {p.tournament&&<div className="tournament-card"><div className="tournament-label"><span><Flag size={14}/>{p.tournament.event}</span><span className="status"><span/>{p.tournament.status}</span></div><div className="stats"><div><span>CHIP COUNT</span><strong>{p.tournament.chips.toLocaleString()}</strong></div><div><span>BIG BLINDS</span><strong>{(p.tournament.chips/p.tournament.bigBlind).toFixed(1)}<small> BB</small></strong></div><div><span>PLAYERS LEFT</span><strong>{p.tournament.remaining||'—'}</strong></div></div></div>}
 {p.hand&&<div className="hand-card"><div className="hand-context"><span>{p.hand.game}</span><span>{p.hand.stakes}</span><span>{p.hand.stack} effective</span></div><div className="card-layout"><div><span className="card-label">HERO · {p.hand.position}</span><Cards cards={p.hand.hero}/></div><div><span className="card-label">{p.hand.board.trim()?'BOARD':'PREFLOP'}</span>{p.hand.board?<Cards cards={p.hand.board}/>:<span className="preflop-note">No community cards</span>}</div>{p.hand.pot&&<div className="pot"><span className="card-label">POT</span><strong>{p.hand.pot}</strong></div>}</div><p className="hand-action">{p.hand.action}</p><h3>{p.hand.question}</h3><div className="vote-buttons">{(['Fold','Call','Raise'] as const).map(choice=><button disabled={busy} className={p.myVote===choice?'chosen':''} key={choice} onClick={()=>mutate('vote',{postId:p.id,choice})}>{p.myVote===choice&&<Check size={13}/>} {choice}<span>{p.votes[choice]}</span></button>)}</div><div className="hand-result">{p.hand.revealed?<p><b>THE RESULT</b>{p.hand.result}</p>:<><span><Eye size={14}/> Result hidden. Discuss the decision first.</span>{(p.userId===user.id||signedOut)&&p.hand.result&&<button onClick={()=>mutate('reveal',{postId:p.id})}>Reveal result</button>}</>}</div></div>}
 <div className="post-actions"><button disabled={busy} className={p.liked?'liked':''} onClick={()=>mutate('like',{postId:p.id,liked:!p.liked})}><Heart size={17} fill={p.liked?'currentColor':'none'}/><span>{p.likes||''} {p.kind==='update'?'On the rail':'Likes'}</span></button><button onClick={()=>setExpanded(old=>old.includes(p.id)?old.filter(id=>id!==p.id):[...old,p.id])}><MessageCircle size={17}/>{p.comments.length||''} Comments</button>{p.kind==='hand'&&<button className="analyze" aria-label="Analyze spot in Spot Solver" title="Analyze spot in Spot Solver" onClick={()=>openSolver(p)}><ChartNoAxesCombined size={16}/> Analyze spot in Spot Solver</button>}</div>
 {expanded.includes(p.id)&&<div className="comments">{p.comments.map(c=><div className="comment" key={c.id}><Avatar name={c.name} small/><div><strong>{c.name}</strong><p>{c.body}</p></div></div>)}<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const body=String(new FormData(form).get('comment')||'').trim();if(body&&await mutate('comment',{postId:p.id,body}))form.reset()}}><input name="comment" required maxLength={2000} aria-label="Write a comment" placeholder="Add to the conversation…"/><button disabled={busy} className="icon-button" aria-label="Send comment"><Send size={18}/></button></form></div>}
 </article>)}<div className="feed-end"><Spade size={13}/> Good company. Better poker.</div></>}
 </>}
 </main><aside className="right-sidebar"><section className="rail-members panel"><div className="section-heading"><span>ON YOUR RAIL</span><Users size={15}/></div><div className="avatar-stack">{members.map(m=>m.name).slice(0,5).map(n=><Avatar key={n} name={n}/>)}</div><p>{current?.members||0} people in your corner.</p><button className="text-link" onClick={()=>open('invite')}>Bring your people in <ArrowUpRight size={16}/></button></section>
 <section className="session-panel panel"><div className="section-heading"><span>{signedOut?'SAMPLE TOURNAMENT':'LATEST TOURNAMENT'}</span><Flag size={15}/></div>{latest?<><h3>{latest.event}</h3><div className="session-status"><span className="status"><span/>{latest.status}</span><span>{latest.remaining} left</span></div><div className="session-value">{latest.chips.toLocaleString()}<small>chips</small></div><div className="blind-meter"><span style={{width:Math.min(100,latest.chips/latest.bigBlind)+'%'}}/></div><p>{(latest.chips/latest.bigBlind).toFixed(1)} big blinds</p></>:<p>No tournament updates yet.</p>}</section>
 <section className="study-panel"><div className="eyebrow"><Spade size={14}/> BUILT TO GET BETTER</div><h2>Talk it through.<br/><em>Find your edge.</em></h2><p>Your next great decision starts with a good conversation.</p><button className="text-link" onClick={()=>{setView('feed');setTab('hand')}}>Explore hand discussions <ArrowUpRight size={16}/></button></section><div className="fair-play"><Lock size={13}/><p>Hand discussions are for review after play. Never use group advice during a live hand.</p></div><button className="version-link" onClick={()=>open('about')}>RailSupport V1.2 · Pilot details</button></aside></div>
 <nav className="mobile-nav" aria-label="Mobile navigation"><button onClick={()=>setView('feed')} className={view==='feed'?'active':''}><Radio size={20}/>My rail</button><button onClick={()=>setView('groups')} className={view==='groups'?'active':''}><Users size={20}/>Groups</button><button className="mobile-new" onClick={()=>compose('update')} aria-label="New post"><Plus size={25}/></button><button onClick={()=>{setView('feed');setTab('hand')}}><Spade size={20}/>Hands</button><button onClick={()=>open('account')}><Avatar name={user.name} small/>Profile</button></nav>
 {notice&&<div className="toast" role="status"><Check size={17}/>{notice}</div>}
 {modal&&<Modal wide={modal==='solver'} title={modal==='compose'?(postKind==='hand'?'Discuss a hand':'Update your rail'):modal==='create'?'Create a private rail':modal==='join'?'Join your people':modal==='invite'?'Invite to '+(current?.name||'your rail'):modal==='solver'?'Your study toolkit':modal.startsWith('delete:')?'Delete this post?':modal==='about'?'RailSupport · Version 1.2':'Your RailSupport account'} description={modal==='compose'?`Only members of ${current?.name} can see this post.`:undefined} onClose={()=>setModal('')}>
 {error&&<div className="error" role="alert">{error}</div>}
 {modal==='compose'&&<form onSubmit={submitPost} className="post-form"><div className="compose-toggle"><button type="button" className={postKind==='update'?'selected':''} onClick={()=>setPostKind('update')}><Flag size={16}/>Rail update</button><button type="button" className={postKind==='hand'?'selected':''} onClick={()=>setPostKind('hand')}><Spade size={16}/>Hand discussion</button></div><label className="field">{postKind==='hand'?'Context (optional)':'Your update'}<textarea value={body} onChange={e=>setBody(e.target.value)} placeholder={postKind==='hand'?'What should the group know?':'Chip update, a good run, or a story from the felt…'} maxLength={5000} rows={3}/></label>
 {postKind==='update'?<><label className="checkbox"><input type="checkbox" checked={updateKind==='tournament'} onChange={e=>setUpdateKind(e.target.checked?'tournament':'text')}/> Include tournament details</label>{updateKind==='tournament'&&<div className="form-grid"><div className="full"><Field label="Event" name="event" placeholder="e.g. Weekend Main Event · Day 2" required/></div><Field label="Chip count" name="chips" type="number" required/><Field label="Current big blind" name="bigBlind" type="number" required/><Field label="Players remaining" name="remaining" type="number" required/><label className="field">Status<select name="status">{['Playing','On break','Bagged','Cashed','Out'].map(s=><option key={s}>{s}</option>)}</select></label></div>}</>:<><div className="form-grid">{([['stakes','Stakes / event','$1 / $3 or $400 tournament'],['stack','Effective stack','100 BB'],['hero','Your hole cards','Ah Qh'],['board','Board cards','Qs 9h 4c 7h'],['pot','Pot size','$120']] as const).map(([key,label,placeholder])=><label className="field" key={key}>{label}<input value={hand[key]} onChange={e=>setHand({...hand,[key]:e.target.value})} placeholder={placeholder} maxLength={key==='board'?20:60} required={['hero','stakes','stack'].includes(key)}/></label>)}<label className="field">Position<select value={hand.position} onChange={e=>setHand({...hand,position:e.target.value})}>{['UTG','UTG+1','MP','LJ','HJ','CO','BTN','SB','BB'].map(p=><option key={p}>{p}</option>)}</select></label></div><p className="form-hint">Card notation: A K Q J T 9…2, then h ♥, d ♦, c ♣, or s ♠. Example: Ah Qh. NL Hold’em only in V1.</p><label className="field">Action by street<textarea required value={hand.action} onChange={e=>setHand({...hand,action:e.target.value})} rows={4} placeholder="Preflop: …&#10;Flop: …&#10;Turn: …" maxLength={5000}/></label><label className="field">Your question<input required value={hand.question} onChange={e=>setHand({...hand,question:e.target.value})} placeholder="What would you do here?" maxLength={500}/></label><label className="field">Result — hidden until you reveal it (optional)<textarea value={hand.result} onChange={e=>setHand({...hand,result:e.target.value})} maxLength={2000} rows={2}/></label><label className="checkbox"><input type="checkbox" required/> This hand is finished. I’m posting for review, not live advice.</label></>}
 <div className="form-bottom"><span><Lock size={12}/>{signedOut?'Preview · not saved':'Private to this rail'}</span><button className="primary" disabled={busy}>{busy?'Sharing…':'Share with my rail'}<ArrowUpRight size={16}/></button></div></form>}
 {modal==='create'&&<form className="post-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate('create',{name:f.get('name'),description:f.get('description'),kind:f.get('kind')}))setModal('')}}><p className="muted">Separate spaces for your friends, study partners, and backers. Posts never cross between rails.</p><Field name="name" label="Rail name" placeholder="e.g. Chad’s Rail" required/><Field name="description" label="A short description" placeholder="The people in my corner."/><label className="field">Who is it for?<select name="kind"><option>Friends & family</option><option>Study group</option><option>Backers</option></select></label><button className="primary" disabled={busy}><Plus size={17}/>Create rail</button></form>}
 {modal==='join'&&(signedOut?<div className="setup-note"><Lock size={28}/><h3>Invites connect real accounts.</h3><p>{ready?'Sign in to join a private rail.':'Shared accounts are awaiting database setup. You can explore the sample groups now; joining real people is not enabled yet.'}</p>{ready&&<button className="primary" onClick={()=>open('account')}>Sign in / Create account</button>}</div>:<form className="post-form" onSubmit={async e=>{e.preventDefault();if(await mutate('join',{code:new FormData(e.currentTarget).get('code')}))setModal('')}}><Field name="code" label="Private invite code" placeholder="Paste the code your friend shared" required/><button className="primary" disabled={busy}>Join rail<ArrowUpRight size={16}/></button></form>)}
 {modal==='invite'&&(signedOut||!current?<div className="setup-note"><Users size={28}/><h3>Your real rail is next.</h3><p>{ready?'Sign in and create your own private rail to invite friends.':'This preview has no active invite codes. Once accounts are connected, you can invite friends and backers without ChatGPT.'}</p></div>:<div className="post-form"><p className="muted">Send your friends this page link and the code below. Anyone with the code and a RailSupport account can join, so share it privately.</p><label className="field">Invite code<input readOnly value={current.code||''} onFocus={e=>e.target.select()}/></label><button className="primary" onClick={async()=>{try{await navigator.clipboard.writeText(`Join ${current.name} on RailSupport: ${location.origin}\nInvite code: ${current.code}`);setCopied(true)}catch{setError('Select the code above and copy it manually.')}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Copy invitation'}</button></div>)}
 {modal==='solver'&&<SpotSolverPanel post={solverPost}/>}
 {modal==='account'&&<div className="post-form"><Avatar name={user.name}/><h3>{user.name}</h3><p className="muted">Signed in to RailSupport.</p><button className="outline" onClick={async()=>{try{await api('/api/auth/sign-out',{});location.reload()}catch(e){setError((e as Error).message)}}}><LogOut size={17}/> Sign out</button></div>}
 {modal.startsWith('delete:')&&<div className="post-form"><p className="muted">This permanently removes the post and its comments and votes from this rail.</p><div className="form-bottom"><button className="outline" onClick={()=>setModal('')}>Keep post</button><button className="danger" disabled={busy} onClick={async()=>{if(await mutate('delete',{postId:modal.split(':')[1]}))setModal('')}}>Delete post</button></div></div>}
 {modal==='about'&&<div className="setup-note"><Spade size={30}/><h3>Your people. Your poker journey.</h3><p>RailSupport is a separate Buz Trio poker project. Circle Pilot is unchanged.</p><p>V1 includes private-group workflows, tournament updates, completed-hand discussions, votes, comments, reactions, and hidden results.</p><p>{signedOut?'This is an interactive preview with fictional data, not a connected multiuser pilot.':'Your posts are saved to your private rails.'}</p><p className="form-hint">No real-money play, staking transactions, live-hand assistance, active advertising, or paid subscriptions.</p></div>}
 </Modal>}
 </div>
}
