'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Spade,Users,Plus,ArrowUpRight,Lock,MessageCircle,Heart,Flag,ChevronDown,ArrowLeft,Copy,Check,Radio,Layers3,LogOut,RefreshCw,Send,Trash2,Eye,ChartNoAxesCombined,Flame,BookOpen,X,Search,ImagePlus,Building2} from 'lucide-react';
import type {Group,Post,User,Hand,Tournament} from '@/lib/types';
import {connectSpotSolver,solverHand,SOLVER_URL, type ImportState} from '@/lib/spot-solver';
import {postSchema} from '@/lib/validation';
import Image from 'next/image';
import OddsPanel from './odds-panel';
import ProfilePanel from './profile-panel';
import dynamic from 'next/dynamic';
import People,{InviteMembers} from './people';
const RoomPages=dynamic(()=>import('./room-pages'),{loading:()=> <div className="panel empty" role="status">Loading rooms…</div>});

function Avatar({name,small=false,photo}:{name:string;small?:boolean;photo?:string}){const letters=name.split(' ').slice(0,2).map(s=>s[0]).join('');return <span className={'avatar '+(small?'small':'')} style={{'--avatar-hue':String((name.charCodeAt(0)*13)%360)} as React.CSSProperties}>{photo?<Image src={photo} alt="" width={small?32:40} height={small?32:40} unoptimized style={{borderRadius:'50%',width:'100%',height:'100%',objectFit:'cover'}}/>:letters}</span>}
function Cards({cards}:{cards:string}){return <span className="playing-cards">{cards.trim().split(/\s+/).filter(Boolean).map((card,i)=><span key={i} className={'playing-card '+(/[hd]$/i.test(card)?'red':'')}><b>{card[0]?.toUpperCase()}</b><span>{{h:'♥',d:'♦',c:'♣',s:'♠'}[card[1]?.toLowerCase()]}</span></span>)}</span>}
function Modal({title,description,children,onClose,wide=false}:{title:string;description?:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[]);return <dialog ref={ref} className="modal" style={wide?{width:"min(1200px, 96vw)",maxWidth:"96vw"}:undefined} aria-labelledby="modal-title" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><div className="modal-head"><div><h2 id="modal-title">{title}</h2>{description&&<p>{description}</p>}</div><button type="button" className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={21}/></button></div>{children}</dialog>}
function Field({label,name,placeholder,required=false,defaultValue='',type='text'}:{label:string;name:string;placeholder?:string;required?:boolean;defaultValue?:string;type?:string}){return <label className="field">{label}<input name={name} placeholder={placeholder} required={required} defaultValue={defaultValue} type={type} min={type==='number'?0:undefined} maxLength={200}/></label>}

function SpotSolverPanel({post}:{post:Post|null}){
 const frame=useRef<HTMLIFrameElement>(null);
 const bridge=useRef<ReturnType<typeof connectSpotSolver>|null>(null);
 const [status,setStatus]=useState<{state:ImportState;message:string}|null>(null);
 useEffect(()=>{
  if(!frame.current)return;
  const connection=connectSpotSolver(frame.current,(state,message)=>setStatus({state,message}));
  bridge.current=connection;
  if(post?.hand)connection.importHand(solverHand(post));
  else setStatus(null);
  return()=>{connection.destroy();bridge.current=null;};
 },[post]);
 return <div className="post-form"><h3>{post?'Analyze this hand in Spot Solver':'Study with Spot Solver'}</h3>
 {!post&&<p className="form-hint">To import a hand automatically, open its discussion post on your rail and tap “Analyze spot in Spot Solver.” The Study Tools button opens the solver without choosing a hand.</p>}
 {status&&<p role="status" aria-live="polite" className={status.state==='rejected'||status.state==='timeout'?'error':'muted'}>{status.message}</p>}
 {post&&<><p className="form-hint">Cards, position, and notes transfer into the analyzer. Original amounts stay in notes: review units, players, pot, amount to call, and ranges. Importing does not run a calculation.</p>{!post.hand&&<p className="error" role="status">This post has no saved hand details to import.</p>}<button className="outline" disabled={!post.hand||status?.state==='pending'} onClick={()=>bridge.current?.importHand(solverHand(post))}>{status?.state==='imported'?'Reimport original hand':'Retry import'}</button></>}
 <iframe ref={frame} src={SOLVER_URL} title="Spot Solver poker study tools" referrerPolicy="no-referrer" style={{width:'100%',height:'72dvh',minHeight:480,border:'1px solid #394332',borderRadius:12,background:'#050c09'}}/>
 <a className="outline" href={SOLVER_URL} target="_blank" rel="noopener noreferrer">Open Spot Solver separately <ArrowUpRight size={16}/></a><p className="form-hint">Hand import works in this panel, not the separate tab. Spot Solver accounts are separate from Rail Social.</p></div>;
}

const newHand:Hand={game:'NL Hold’em',stakes:'',position:'BTN',stack:'',hero:'',board:'',pot:'',action:'',question:'',result:'',revealed:false};
async function resizePostPhoto(file:File){
 if(!/^image\/(jpeg|png|webp|heic|heif)$/.test(file.type)||file.size>12_000_000)throw Error('Choose a JPG, PNG, WebP, or HEIC photo under 12 MB.');
 const image=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,1600/Math.max(image.width,image.height));
 canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));
 const context=canvas.getContext('2d');if(!context){image.close();throw Error('Photo processing is unavailable in this browser.');}
 context.drawImage(image,0,0,canvas.width,canvas.height);image.close();
 for(const quality of [.78,.64,.48,.32]){const value=canvas.toDataURL('image/jpeg',quality);if(value.length<=400000)return value;}
 throw Error('This photo is still too large. Choose a smaller image.');
}

export default function RailApp({ready}:{ready:boolean}){
 const [user,setUser]=useState<User>({id:'',name:''}),[signedOut,setSignedOut]=useState(true),[groups,setGroups]=useState<Group[]>([]),[posts,setPosts]=useState<Post[]>([]),[active,setActive]=useState(''),[members,setMembers]=useState<User[]>([]),[following,setFollowing]=useState<string[]>([]),[tab,setTab]=useState('all'),[view,setView]=useState('feed');
 const [modal,setModal]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[expanded,setExpanded]=useState<string[]>([]),[copied,setCopied]=useState(false),[authMode,setAuthMode]=useState('signup');
 const [body,setBody]=useState(''),[hand,setHand]=useState<Hand>(newHand),[images,setImages]=useState<string[]>([]),[photoBusy,setPhotoBusy]=useState(false),[memberSearch,setMemberSearch]=useState(''),[updateKind,setUpdateKind]=useState('text'),[postKind,setPostKind]=useState<'update'|'hand'>('update');
 const [checking,setChecking]=useState(ready);
 const [solverPost,setSolverPost]=useState<Post|null>(null);
 const [oddsHand,setOddsHand]=useState<Hand|null>(null);
 const [profileId,setProfileId]=useState('');
 const [inviteCode,setInviteCode]=useState('');
 const [invitationCount,setInvitationCount]=useState(0);
 useEffect(()=>{if(signedOut)return;const c=new AbortController();const refresh=()=>fetch('/api/community',{signal:c.signal}).then(r=>r.ok?r.json():null).then(d=>{if(d&&!c.signal.aborted)setInvitationCount(d.invitations.length)}).catch(()=>{});void refresh();const timer=setInterval(refresh,60000);return()=>{c.abort();clearInterval(timer)}},[signedOut,view]);
 function openSolver(post:Post|null=null){setSolverPost(post);setCopied(false);open('solver');}
 function openOdds(post:Post|null=null){setOddsHand(post?.hand||null);open('odds');}
 function openProfile(id:string){setProfileId(id);open('profile');}
 useEffect(()=>{const sync=()=>{const p=new URLSearchParams(location.search);setView(p.has('room')||p.get('view')==='rooms'?'rooms':p.get('view')==='groups'?'groups':p.get('view')==='people'?'people':'feed');};sync();window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[]);
 function navigateView(next:string){setView(next);const url=new URL(location.href);if(next==='feed')url.searchParams.delete('view');else url.searchParams.set('view',next);if(next!=='rooms'){url.searchParams.delete('room');url.searchParams.delete('joinRoom');}history.pushState(null,'',url);}
 const activeRef=useRef(active);activeRef.current=active;
 const current=groups.find(g=>g.id===active);
 const filtered=posts.filter(p=>p.groupId===active&&(tab==='all'||(tab==='following'?following.includes(p.userId):p.kind===tab)));
 const latest=posts.find(p=>p.groupId===active&&p.tournament)?.tournament;
 const matchingMembers=members.filter(m=>m.name.toLocaleLowerCase().includes(memberSearch.trim().toLocaleLowerCase()));
 async function api(path:string,values?:Record<string,unknown>){const res=await fetch(path,values?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)}:undefined);const data=await res.json();if(!res.ok)throw Error(data.error||data.message||'Something went wrong. Please try again.');return data;}
 const loadGroup=useCallback(async(id:string)=>{if(!id)return;const data=await api('/api/rail?group='+encodeURIComponent(id));if(activeRef.current===id){setPosts(data.posts);setMembers(data.members);setFollowing(data.following);}},[]);
 async function loadAccount(select?:string){const data=await api('/api/rail');setUser(data.user);setGroups(data.groups);setSignedOut(false);setPosts([]);setActive(select||data.groups[0]?.id||'');}
 useEffect(()=>{const code=new URLSearchParams(location.search).get('invite');if(code&&/^[a-f0-9]{36}$/i.test(code)){setInviteCode(code);setModal('join')}},[]);
 useEffect(()=>{if(!signedOut&&inviteCode)setModal('join')},[signedOut,inviteCode]);
 useEffect(()=>{if(signedOut)return;const id=new URLSearchParams(location.search).get('profile');if(id&&id.length<=100&&!new URLSearchParams(location.search).has('invite')){setProfileId(id);setModal('profile')}},[signedOut]);
 useEffect(()=>{if(!ready)return;fetch('/api/rail').then(async r=>{if(r.status===401)return;if(!r.ok)throw Error('Could not reconnect. Your saved posts have not been changed.');const d=await r.json();setUser(d.user);setGroups(d.groups);setSignedOut(false);setPosts([]);setActive(d.groups[0]?.id||'')}).catch(e=>setError(e.message)).finally(()=>setChecking(false));},[ready]);
 useEffect(()=>{if(signedOut||!active)return;setLoading(true);loadGroup(active).catch(e=>setError(e.message)).finally(()=>setLoading(false));const timer=setInterval(()=>loadGroup(active).catch(()=>{}),20000);return()=>clearInterval(timer);},[signedOut,active,loadGroup]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(timer)},[notice]);
 function open(kind:string){setError('');setModal(kind);}
 async function mutate(action:string,data:Record<string,unknown>={}){
  if(busy)return false;setBusy(true);setError('');try{
   if(signedOut)throw Error('Sign in before posting.');
   const res=await api('/api/rail',{action,...data});if(action==='create'||action==='join'){await loadAccount(res.id);navigateView('feed');setTab('all');}else await loadGroup(active);
   return true;
  }catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}
 }
 async function authenticate(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!ready)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await api('/api/auth/'+(authMode==='signup'?'sign-up/email':'sign-in/email'),{name:f.get('name'),email:f.get('email'),password:f.get('password')});await loadAccount();setModal(inviteCode?'join':'');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function submitPost(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(photoBusy)return;const f=new FormData(e.currentTarget);let tournament:Tournament|undefined;if(postKind==='update'&&updateKind==='tournament')tournament={event:String(f.get('event')),chips:Number(f.get('chips')),bigBlind:Number(f.get('bigBlind')),remaining:Number(f.get('remaining')),status:f.get('status') as Tournament['status']};const data={groupId:active,kind:postKind,body,images,hand:postKind==='hand'?hand:undefined,tournament};const parsed=postSchema.safeParse(data);if(!parsed.success){setError(parsed.error.issues[0].message);return}if(await mutate('post',parsed.data)){setBody('');setHand(newHand);setImages([]);setModal('');setTab('all');}}
 async function addPhotos(files:FileList|null){if(!files?.length)return;setError('');if(images.length+files.length>3){setError('Add up to three photos per post.');return}setPhotoBusy(true);try{const resized=await Promise.all(Array.from(files).map(resizePostPhoto));setImages(old=>[...old,...resized].slice(0,3))}catch(e){setError((e as Error).message)}finally{setPhotoBusy(false)}}
 function compose(kind:'update'|'hand'){if(!current){open('create');return}setPostKind(kind);open('compose');}
 if(signedOut)return <div className="app-shell"><div className="stage-background" aria-hidden="true"/><main style={{maxWidth:480,margin:'0 auto',padding:'64px 20px'}}><section className="panel" style={{padding:28}}><Image className="login-logo" loading="eager" src="/railsocial-logo.png" alt="Rail Social" width={250} height={82}/><h1>Your people. Your poker.</h1><p className="muted">{inviteCode?'Sign in or create an account to accept your rail invitation.':'Create your account, start a private rail, and invite your friends.'}</p>{error&&<p className="error" role="alert">{error}</p>}{checking?<p role="status">Checking your account…</p>:ready?<form className="post-form" onSubmit={authenticate}><p className="muted">Your own Rail Social account.</p><div className="compose-toggle"><button type="button" className={authMode==='signup'?'selected':''} onClick={()=>{setAuthMode('signup');setError('')}}>Create account</button><button type="button" className={authMode==='signin'?'selected':''} onClick={()=>{setAuthMode('signin');setError('')}}>Sign in</button></div>{authMode==='signup'&&<Field name="name" label="Display name" required/>}<Field name="email" label="Email" type="email" required/><label className="field">Password<input name="password" type="password" minLength={8} maxLength={128} required autoComplete={authMode==='signup'?'new-password':'current-password'}/></label><p className="form-hint">Use at least 8 characters. Email verification and self-service password recovery are not enabled in this pilot.</p><button className="primary" disabled={busy}>{busy?'Please wait…':authMode==='signup'?'Create account':'Sign in'}</button></form>:<p role="status">Account setup is being completed. Please check back shortly.</p>}</section></main></div>;
 return <div className="app-shell"><div className="stage-background" aria-hidden="true"/><header className="topbar"><a href="/" className="brand"><Image className="brand-image" src="/railsocial-logo.png" alt="Rail Social" width={184} height={60}/><span className="beta">V2.2</span></a><nav className="topnav" aria-label="Main navigation"><button className={view==='feed'?'active':''} onClick={()=>navigateView('feed')}>My rail</button><button className={view==='groups'?'active':''} onClick={()=>navigateView('groups')}>My groups</button><button className={view==='rooms'?'active':''} onClick={()=>navigateView('rooms')}>Rooms</button><button className={view==='people'?'active':''} onClick={()=>navigateView('people')}>People{invitationCount>0?' ('+invitationCount+')':''}</button><button onClick={()=>open('odds')}>Odds calculator</button><button onClick={()=>openSolver()}>Study tools</button></nav><button className="account" aria-label="Open account settings" onClick={()=>open('account')}><Avatar name={user.name} photo={user.photo} small/><span>{user.name}</span><ChevronDown size={14}/></button></header>

 <div className={'layout '+(view==='rooms'||view==='people'?'rooms-layout':'')}><aside className="left-sidebar"><div className="sidebar-caption">YOUR INNER CIRCLE</div><h2>Your people.<br/><em>Your poker.</em></h2><div className="sidebar-separator"/><div className="section-heading"><span>MY PRIVATE RAILS</span><span>{groups.length.toString().padStart(2,'0')}</span></div><div className="rail-list">{groups.map((g,i)=><button key={g.id} disabled={busy} className={'rail-link '+(g.id===active?'selected':'')} onClick={()=>{setActive(g.id);navigateView('feed');setTab('all');setError('')}}><span className={'rail-icon tone-'+i%3}>{g.kind==='Study group'?<Spade size={19}/>:g.kind==='Backers'?<Layers3 size={19}/>:<Users size={19}/>}</span><span>{g.name}<small>{g.kind}</small></span>{g.id===active&&<span className="selection-mark"/>}</button>)}</div><button className="sidebar-action" onClick={()=>open('create')}><Plus size={17}/> Create a private rail</button><button className="sidebar-action" onClick={()=>open('join')}><ArrowUpRight size={17}/> Join with an invite</button><div className="privacy-note"><Lock size={17}/><div>Invite only. Always.<p>Every rail has its own members and its own conversations.</p></div></div><div className="sidebar-footer">A BUZ TRIO PROJECT <span>♠</span></div></aside>
 <main className="main-content">{error&&!modal&&<div className="error" role="alert">{error}</div>}
 {view==='people'?<People openProfile={openProfile} onJoined={async target=>{if(target.groupId){await loadAccount(target.groupId);navigateView('feed');setTab('all')}else if(target.roomId){const url=new URL('/',location.origin);url.searchParams.set('view','rooms');url.searchParams.set('room',target.roomId);history.pushState(null,'',url);setView('rooms');window.dispatchEvent(new PopStateEvent('popstate'))}}}/>:view==='rooms'?<RoomPages/>:view==='groups'?<><div className="page-title"><div><span className="eyebrow">A SEAT FOR YOUR PEOPLE</span><h1>My private rails</h1></div><button className="primary" onClick={()=>open('create')}><Plus size={17}/> New rail</button></div><div className="group-grid">{groups.map(g=><button className="group-card panel" key={g.id} onClick={()=>{setActive(g.id);navigateView('feed')}}><Users size={26}/><span className="eyebrow">{g.kind}</span><h2>{g.name}</h2><p>{g.description}</p><span>{g.members} members <ArrowUpRight size={16}/></span></button>)}</div></>:<>
 <div className="page-title"><div><span className="eyebrow"><Lock size={12}/> YOUR PRIVATE RAIL</span><h1>{current?.name||'Make your first rail.'}</h1><p>{current?.description||'Bring your friends, study partners, or backers together.'}</p></div>{current&&<div className="rail-title-actions"><button className="outline" onClick={()=>{setMemberSearch('');open('members')}} aria-label="Search rail members"><Search size={16}/> Members</button><button className="outline" onClick={()=>open('invite')}><Users size={16}/> Invite friends</button></div>}</div>
 {!current?<section className="empty panel"><Spade size={36}/><h2>Every player needs a rail.</h2><p>Create a private space for the people in your corner.</p><button className="primary" onClick={()=>open('create')}><Plus size={17}/> Create my rail</button></section>:<>
 <section className="composer panel"><div className="composer-prompt"><Avatar name={user.name} photo={user.photo}/><button onClick={()=>compose('update')}>What’s happening on your side of the felt?</button></div><div className="composer-actions"><button onClick={()=>{setUpdateKind('tournament');compose('update')}}><Flag size={17}/><span>Tournament update</span></button><button onClick={()=>compose('hand')}><Spade size={17}/><span>Discuss a hand</span></button><button onClick={()=>open('odds')}><ChartNoAxesCombined size={17}/><span>Odds</span></button><button className="share-button" onClick={()=>{setUpdateKind('text');compose('update')}}>New post <Plus size={16}/></button></div></section>
 <div className="feed-tabs" role="tablist" aria-label="Post type">{[['all','All activity'],['following','Following'],['update','Rail updates'],['hand','Hand discussions']].map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}<button className="refresh icon-button" aria-label="Refresh activity" onClick={()=>loadGroup(active).catch(e=>setError(e.message))}><RefreshCw size={15}/></button></div>
 {loading?<div className="panel empty"><RefreshCw className="spin"/><p>Loading your rail…</p></div>:filtered.length===0?<div className="panel empty"><MessageCircle size={30}/><h2>{tab==='following'?'No followed players here yet.':'Start the conversation.'}</h2><p>{tab==='following'?'Follow a member from their profile to see their posts in this rail. Following does not unlock private rails.':'Share an update or a hand you’ve finished playing.'}</p>{tab!=='following'&&<button className="outline" onClick={()=>compose('update')}>Write the first post</button>}</div>:filtered.map(p=><article className="post panel" key={p.id}><div className="post-head"><button className="profile-link" onClick={()=>openProfile(p.userId)} aria-label={'View '+p.name+' profile'}><Avatar name={p.name} photo={p.photo}/></button><div><button className="profile-name" onClick={()=>openProfile(p.userId)}>{p.name}</button><div className="post-meta">{new Date(p.created).toLocaleDateString(undefined,{month:'short',day:'numeric'})}<span>·</span><Lock size={10}/>{current.name}</div></div><span className={'post-kind '+p.kind}>{p.kind==='hand'?<><Spade size={12}/> HAND DISCUSSION</>:<><Flag size={12}/> RAIL UPDATE</>}</span>{p.userId===user.id&&<button className="icon-button delete-post" aria-label="Delete post" onClick={()=>open('delete:'+p.id)}><Trash2 size={14}/></button>}</div>
 {p.body&&<p className="post-body">{p.body}</p>}
 {p.imageCount>0&&<div className={'post-images count-'+p.imageCount}>{Array.from({length:p.imageCount},(_,index)=><Image key={index} src={'/api/post-image?post='+encodeURIComponent(p.id)+'&position='+index} alt={'Photo '+(index+1)+' shared by '+p.name} width={800} height={600} unoptimized/>)}</div>}
 {p.tournament&&<div className="tournament-card"><div className="tournament-label"><span><Flag size={14}/>{p.tournament.event}</span><span className="status"><span/>{p.tournament.status}</span></div><div className="stats"><div><span>CHIP COUNT</span><strong>{p.tournament.chips.toLocaleString()}</strong></div><div><span>BIG BLINDS</span><strong>{(p.tournament.chips/p.tournament.bigBlind).toFixed(1)}<small> BB</small></strong></div><div><span>PLAYERS LEFT</span><strong>{p.tournament.remaining||'—'}</strong></div></div></div>}
 {p.hand&&<div className="hand-card"><div className="hand-context"><span>{p.hand.game}</span><span>{p.hand.stakes}</span><span>{p.hand.stack} effective</span></div><div className="card-layout"><div><span className="card-label">HERO · {p.hand.position}</span><Cards cards={p.hand.hero}/></div><div><span className="card-label">{p.hand.board.trim()?'BOARD':'PREFLOP'}</span>{p.hand.board?<Cards cards={p.hand.board}/>:<span className="preflop-note">No community cards</span>}</div>{p.hand.pot&&<div className="pot"><span className="card-label">POT</span><strong>{p.hand.pot}</strong></div>}</div><p className="hand-action">{p.hand.action}</p><h3>{p.hand.question}</h3><div className="vote-buttons">{(['Fold','Call','Raise'] as const).map(choice=><button disabled={busy} className={p.myVote===choice?'chosen':''} key={choice} onClick={()=>mutate('vote',{postId:p.id,choice})}>{p.myVote===choice&&<Check size={13}/>} {choice}<span>{p.votes[choice]}</span></button>)}</div><div className="hand-result">{p.hand.revealed?<p><b>THE RESULT</b>{p.hand.result}</p>:<><span><Eye size={14}/> Result hidden. Discuss the decision first.</span>{(p.userId===user.id||signedOut)&&p.hand.result&&<button onClick={()=>mutate('reveal',{postId:p.id})}>Reveal result</button>}</>}</div></div>}
 <div className="post-actions"><button disabled={busy} className={p.liked?'liked':''} onClick={()=>mutate('like',{postId:p.id,liked:!p.liked})}><Heart size={17} fill={p.liked?'currentColor':'none'}/><span>{p.likes||''} {p.kind==='update'?'On the rail':'Likes'}</span></button><button onClick={()=>setExpanded(old=>old.includes(p.id)?old.filter(id=>id!==p.id):[...old,p.id])}><MessageCircle size={17}/>{p.comments.length||''} Comments</button>{p.kind==='hand'&&<><button onClick={()=>openOdds(p)}><ChartNoAxesCombined size={16}/> Odds</button><button className="analyze" aria-label="Analyze spot in Spot Solver" title="Analyze spot in Spot Solver" onClick={()=>openSolver(p)}><ChartNoAxesCombined size={16}/> Analyze spot in Spot Solver</button></>}</div>
 {expanded.includes(p.id)&&<div className="comments">{p.comments.map(c=><div className="comment" key={c.id}><Avatar name={c.name} small/><div><button className="profile-name" onClick={()=>openProfile(c.userId)}>{c.name}</button><p>{c.body}</p></div></div>)}<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const body=String(new FormData(form).get('comment')||'').trim();if(body&&await mutate('comment',{postId:p.id,body}))form.reset()}}><input name="comment" required maxLength={2000} aria-label="Write a comment" placeholder="Add to the conversation…"/><button disabled={busy} className="icon-button" aria-label="Send comment"><Send size={18}/></button></form></div>}
 </article>)}<div className="feed-end"><Spade size={13}/> Good company. Better poker.</div></>}
 </>}
 </main>{view!=='rooms'&&view!=='people'&&<aside className="right-sidebar"><section className="rail-members panel"><div className="section-heading"><span>ON YOUR RAIL</span><Users size={15}/></div><div className="avatar-stack">{members.slice(0,5).map(m=><button className="profile-link" key={m.id} title={'View '+m.name} onClick={()=>openProfile(m.id)}><Avatar name={m.name} photo={m.photo}/></button>)}</div><p>{current?.members||0} people in your corner.</p><div className="member-list">{members.slice(0,8).map(m=><button key={m.id} onClick={()=>openProfile(m.id)}>{m.name}</button>)}</div><button className="text-link" onClick={()=>{setMemberSearch('');open('members')}}><Search size={16}/> Search members</button><button className="text-link" style={{marginTop:12}} onClick={()=>open('invite')}>Bring your people in <ArrowUpRight size={16}/></button></section>
 <section className="session-panel panel"><div className="section-heading"><span>{signedOut?'SAMPLE TOURNAMENT':'LATEST TOURNAMENT'}</span><Flag size={15}/></div>{latest?<><h3>{latest.event}</h3><div className="session-status"><span className="status"><span/>{latest.status}</span><span>{latest.remaining} left</span></div><div className="session-value">{latest.chips.toLocaleString()}<small>chips</small></div><div className="blind-meter"><span style={{width:Math.min(100,latest.chips/latest.bigBlind)+'%'}}/></div><p>{(latest.chips/latest.bigBlind).toFixed(1)} big blinds</p></>:<p>No tournament updates yet.</p>}</section>
 <section className="study-panel"><div className="eyebrow"><Spade size={14}/> BUILT TO GET BETTER</div><h2>Talk it through.<br/><em>Find your edge.</em></h2><p>Your next great decision starts with a good conversation.</p><button className="text-link" onClick={()=>{navigateView('feed');setTab('hand')}}>Explore hand discussions <ArrowUpRight size={16}/></button><button className="text-link" style={{marginTop:16}} onClick={()=>open('odds')}>Calculate hand odds <ArrowUpRight size={16}/></button></section><div className="fair-play"><Lock size={13}/><p>Hand discussions are for review after play. Never use group advice during a live hand.</p></div><button className="version-link" onClick={()=>open('about')}>Rail Social V2.2 · Pilot details</button></aside>}</div>
 <nav className="mobile-nav" aria-label="Mobile navigation"><button onClick={()=>navigateView('feed')} className={view==='feed'?'active':''}><Radio size={20}/>My rail</button><button onClick={()=>navigateView('groups')} className={view==='groups'?'active':''}><Users size={20}/>Groups</button><button onClick={()=>navigateView('rooms')} className={view==='rooms'?'active':''}><Building2 size={20}/>Rooms</button><button onClick={()=>navigateView('people')} className={view==='people'?'active':''}><Users size={20}/>People{invitationCount>0?' ('+invitationCount+')':''}</button><button onClick={()=>open('odds')}><ChartNoAxesCombined size={20}/>Odds</button><button onClick={()=>openProfile(user.id)}><Avatar name={user.name} photo={user.photo} small/>Profile</button></nav>
 {notice&&<div className="toast" role="status"><Check size={17}/>{notice}</div>}
 {modal&&<Modal wide={modal==='solver'||modal==='profile'} title={modal==='compose'?(postKind==='hand'?'Discuss a hand':'Update your rail'):modal==='create'?'Create a private rail':modal==='join'?'Join your people':modal==='members'?'Members of '+(current?.name||'your rail'):modal==='invite'?'Invite to '+(current?.name||'your rail'):modal==='solver'?'Your study toolkit':modal==='odds'?'Hand vs hand odds':modal==='profile'?'Player profile':modal.startsWith('delete:')?'Delete this post?':modal==='about'?'Rail Social · Version 2.2':'Your Rail Social account'} description={modal==='compose'?`Only members of ${current?.name} can see this post.`:undefined} onClose={()=>{setModal('');setOddsHand(null)}}>
 {error&&<div className="error" role="alert">{error}</div>}
 {modal==='compose'&&<form onSubmit={submitPost} className="post-form"><div className="compose-toggle"><button type="button" className={postKind==='update'?'selected':''} onClick={()=>setPostKind('update')}><Flag size={16}/>Rail update</button><button type="button" className={postKind==='hand'?'selected':''} onClick={()=>setPostKind('hand')}><Spade size={16}/>Hand discussion</button></div><label className="field">{postKind==='hand'?'Context (optional)':'Your update'}<textarea value={body} onChange={e=>setBody(e.target.value)} placeholder={postKind==='hand'?'What should the group know?':'Chip update, a good run, or a story from the felt…'} maxLength={5000} rows={3}/></label>
 <label className="field">Photos (up to 3)<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple onChange={e=>{void addPhotos(e.target.files);e.target.value=''}}/><span className="form-hint">Photos are resized before posting and shown only to members of this rail.</span></label>{photoBusy&&<p role="status" className="form-hint">Preparing photos…</p>}{images.length>0&&<div className="photo-previews">{images.map((src,index)=><div key={index}><Image src={src} alt={'Photo '+(index+1)+' preview'} width={140} height={105} unoptimized/><button type="button" aria-label={'Remove photo '+(index+1)} onClick={()=>setImages(old=>old.filter((_,i)=>i!==index))}><X size={16}/></button></div>)}</div>}
 {postKind==='update'?<><label className="checkbox"><input type="checkbox" checked={updateKind==='tournament'} onChange={e=>setUpdateKind(e.target.checked?'tournament':'text')}/> Include tournament details</label>{updateKind==='tournament'&&<div className="form-grid"><div className="full"><Field label="Event" name="event" placeholder="e.g. Weekend Main Event · Day 2" required/></div><Field label="Chip count" name="chips" type="number" required/><Field label="Current big blind" name="bigBlind" type="number" required/><Field label="Players remaining" name="remaining" type="number" required/><label className="field">Status<select name="status">{['Playing','On break','Bagged','Cashed','Out'].map(s=><option key={s}>{s}</option>)}</select></label></div>}</>:<><div className="form-grid">{([['stakes','Stakes / event','$1 / $3 or $400 tournament'],['stack','Effective stack','100 BB'],['hero','Your hole cards','Ah Qh'],['board','Board cards','Qs 9h 4c 7h'],['pot','Pot size','$120']] as const).map(([key,label,placeholder])=><label className="field" key={key}>{label}<input value={hand[key]} onChange={e=>setHand({...hand,[key]:e.target.value})} placeholder={placeholder} maxLength={key==='board'?20:60} required={['hero','stakes','stack'].includes(key)}/></label>)}<label className="field">Position<select value={hand.position} onChange={e=>setHand({...hand,position:e.target.value})}>{['UTG','UTG+1','MP','LJ','HJ','CO','BTN','SB','BB'].map(p=><option key={p}>{p}</option>)}</select></label></div><p className="form-hint">Card notation: A K Q J T 9…2, then h ♥, d ♦, c ♣, or s ♠. Example: Ah Qh. NL Hold’em only in V1.</p><label className="field">Action by street<textarea required value={hand.action} onChange={e=>setHand({...hand,action:e.target.value})} rows={4} placeholder="Preflop: …&#10;Flop: …&#10;Turn: …" maxLength={5000}/></label><label className="field">Your question<input required value={hand.question} onChange={e=>setHand({...hand,question:e.target.value})} placeholder="What would you do here?" maxLength={500}/></label><label className="field">Result — hidden until you reveal it (optional)<textarea value={hand.result} onChange={e=>setHand({...hand,result:e.target.value})} maxLength={2000} rows={2}/></label><label className="checkbox"><input type="checkbox" required/> This hand is finished. I’m posting for review, not live advice.</label></>}
 <div className="form-bottom"><span><Lock size={12}/>{signedOut?'Preview · not saved':'Private to this rail'}</span><button className="primary" disabled={busy||photoBusy}>{busy?'Sharing…':'Share with my rail'}<ArrowUpRight size={16}/></button></div></form>}
 {modal==='members'&&<div className="post-form"><p className="muted">Find people already in this private rail. Select a player to view their profile.</p><label className="field">Search by name<input type="search" value={memberSearch} onChange={e=>setMemberSearch(e.target.value)} placeholder="Search members" autoFocus/></label><div className="member-results">{matchingMembers.map(m=><button key={m.id} onClick={()=>openProfile(m.id)}><Avatar name={m.name} photo={m.photo} small/><span>{m.name}</span><ArrowUpRight size={15}/></button>)}{matchingMembers.length===0&&<p className="muted">No members match that name.</p>}</div><button className="outline" onClick={()=>open('invite')}>Invite another player</button></div>}
 {modal==='create'&&<form className="post-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate('create',{name:f.get('name'),description:f.get('description'),kind:f.get('kind')}))setModal('')}}><p className="muted">Separate spaces for your friends, study partners, and backers. Posts never cross between rails.</p><Field name="name" label="Rail name" placeholder="e.g. Chad’s Rail" required/><Field name="description" label="A short description" placeholder="The people in my corner."/><label className="field">Who is it for?<select name="kind"><option>Friends & family</option><option>Study group</option><option>Backers</option></select></label><button className="primary" disabled={busy}><Plus size={17}/>Create rail</button></form>}
 {modal==='join'&&<form className="post-form" onSubmit={async e=>{e.preventDefault();if(await mutate('join',{code:new FormData(e.currentTarget).get('code')})){setModal('');setInviteCode('');history.replaceState(null,'',location.pathname)}}}><p className="muted">Joining adds you to this private rail. Only its members can see its posts.</p><Field name="code" label="Invite link or code" placeholder="Paste the link your friend shared" defaultValue={inviteCode} required/><button className="primary" disabled={busy}>Join rail<ArrowUpRight size={16}/></button></form>}
 {modal==='invite'&&current&&<div className="post-form"><p className="muted">Share this invite link privately. Your friend can open it, create an account or sign in, then tap Join rail.</p><label className="field">Invite link<input readOnly value={`${typeof location==='undefined'?'https://railsupport.vercel.app':location.origin}/?invite=${current.code}`} onFocus={e=>e.target.select()}/></label><button className="primary" onClick={async()=>{try{await navigator.clipboard.writeText(`${location.origin}/?invite=${current.code}`);setCopied(true)}catch{setError('Select the link above and copy it manually.')}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Link copied':'Copy invite link'}</button><p className="form-hint">Anyone holding the link can request to join, so only send it to people you trust.</p><InviteMembers groupId={current.id}/></div>}
 {modal==='solver'&&<SpotSolverPanel post={solverPost}/>}
 {modal==='odds'&&<OddsPanel hand={oddsHand}/>}
 {modal==='profile'&&<ProfilePanel key={profileId||user.id} id={profileId||user.id} me={user.id} onChanged={()=>{loadGroup(active).catch(()=>{});api('/api/rail').then(d=>setUser(d.user)).catch(()=>{})}}/>}
 {modal==='account'&&<div className="post-form"><Avatar name={user.name} photo={user.photo}/><h3>{user.name}</h3><p className="muted">Signed in to Rail Social.</p><button className="outline" onClick={()=>openProfile(user.id)}>View and edit my profile</button><button className="outline" onClick={async()=>{try{await api('/api/auth/sign-out',{});location.reload()}catch(e){setError((e as Error).message)}}}><LogOut size={17}/> Sign out</button></div>}
 {modal.startsWith('delete:')&&<div className="post-form"><p className="muted">This permanently removes the post and its comments and votes from this rail.</p><div className="form-bottom"><button className="outline" onClick={()=>setModal('')}>Keep post</button><button className="danger" disabled={busy} onClick={async()=>{if(await mutate('delete',{postId:modal.split(':')[1]}))setModal('')}}>Delete post</button></div></div>}
 {modal==='about'&&<div className="setup-note"><Spade size={30}/><h3>Your people. Your poker journey.</h3><p>Rail Social is the new name for the RailSupport poker project. Circle Pilot is unchanged.</p><p>Version 2.2 adds People, in-app invitations, room conversations, and league schedules and standings.</p><p>Version 2.1 adds room pages, room following, host announcements, and owner-managed host invitations.</p><p>Version 2.0 adds invite links, player profiles, member search within each rail, photo posts, follow/unfollow, block/unblock, and hand-versus-hand odds for preflop through river.</p><p>Your posts remain in their private rails. Following someone does not grant access to a private rail.</p><p className="form-hint">No real-money play, staking transactions, live-hand assistance, active advertising, or paid subscriptions.</p></div>}
 </Modal>}
 </div>
}
