'use client';
import {useEffect,useRef,useState} from 'react';
import {communityRequest} from './community-client';
import './community.css';
type League={id:string;name:string;rules:string;active:boolean;joined:boolean};
type Event={id:string;name:string;starts:string;details:string;status:'scheduled'|'completed'|'cancelled'};
type Data={leagues:League[];leagueId:string|null;events:Event[];standings:{id:string;name:string;points:number;played:number}[];results:{eventId:string;userId:string;name:string;place:number;points:number}[]};
const localDate=(value:string)=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
export default function RoomLeague({roomId,managing,canJoin}:{roomId:string;managing:boolean;canJoin:boolean}){
 const [data,setData]=useState<Data|null>(null),[leagueId,setLeagueId]=useState(''),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState<Event|null>(null),[newLeague,setNewLeague]=useState(false),[editLeague,setEditLeague]=useState(false),[showEvent,setShowEvent]=useState(false);
 const lock=useRef(false),league=data?.leagues.find(l=>l.id===data.leagueId);
 useEffect(()=>{const c=new AbortController();setError('');communityRequest<Data>({kind:'leagues',roomId,...(leagueId?{leagueId}:{})},undefined,c.signal).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[roomId,leagueId,revision]);
 async function act(action:Record<string,unknown>,done?:()=>void){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await communityRequest({}, {...action,roomId});done?.();setRevision(v=>v+1);setNotice('League updated.')}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 return <section className="panel community-section" aria-label="Room leagues"><div className="room-heading"><div><span className="eyebrow">PLAY TOGETHER</span><h2>Room leagues</h2></div>{managing&&<button className="outline" disabled={busy} onClick={()=>{setNewLeague(v=>!v);setEditLeague(false)}}>New league</button>}</div>{error&&<p className="error" role="alert">{error} <button className="text-link" onClick={()=>setRevision(v=>v+1)}>Retry</button></p>}{notice&&<p role="status">{notice}</p>}
 {(newLeague||editLeague)&&managing&&<form key={newLeague?'new':league?.id} className="post-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act({action:newLeague?'createLeague':'editLeague',leagueId:league?.id,name:String(f.get('name')),rules:String(f.get('rules')),active:f.get('active')==='on'},()=>{setNewLeague(false);setEditLeague(false);if(newLeague)setLeagueId('')})}}><label className="field">League / season name<input name="name" required minLength={2} maxLength={100} defaultValue={newLeague?'':league?.name}/></label><label className="field">Rules and scoring<textarea name="rules" maxLength={5000} rows={4} defaultValue={newLeague?'':league?.rules} placeholder="Explain the schedule, how points are awarded, and any tie-break rules."/></label>{!newLeague&&<label><input type="checkbox" name="active" defaultChecked={league?.active}/> Open for new players and events</label>}<div className="room-actions"><button className="primary" disabled={busy}>Save league</button><button type="button" className="outline" onClick={()=>{setNewLeague(false);setEditLeague(false)}}>Cancel</button></div></form>}
 {data&&data.leagues.length>0&&<label className="field">Season<select value={data.leagueId||''} disabled={busy} onChange={e=>{setLeagueId(e.target.value);setEditing(null);setShowEvent(false);setEditLeague(false)}}>{data.leagues.map(l=><option value={l.id} key={l.id}>{l.name}{l.active?'':' · Closed'}</option>)}</select></label>}
 {!data&&!error&&<p role="status">Loading leagues…</p>}{data?.leagues.length===0&&<p className="muted">{managing?'Create a season, schedule games, and record results here.':'Your hosts can create a league for this room.'}</p>}
 {league&&<><h3>{league.name}</h3><p className="community-body">{league.rules||'The hosts have not added scoring rules yet.'}</p><div className="room-actions">{league.active&&canJoin&&!league.joined&&<button className="primary" disabled={busy} onClick={()=>act({action:'joinLeague',leagueId:league.id})}>Join league</button>}{league.joined&&<span className="room-tag">YOU’RE ON THE ROSTER</span>}{!canJoin&&<p>Follow this room to join the league.</p>}{managing&&<><button className="outline" disabled={busy} onClick={()=>{setEditLeague(v=>!v);setNewLeague(false)}}>League settings</button>{league.active&&<button className="outline" disabled={busy} onClick={()=>{setEditing(null);setShowEvent(v=>!v)}}>Schedule game</button>}</>}</div>
 <div className="league-table-wrap"><table className="league-table"><caption>Standings · Completed games only</caption><thead><tr><th scope="col">Rank</th><th scope="col">Player</th><th scope="col">Games</th><th scope="col">Points</th></tr></thead><tbody>{data!.standings.map((p,i,all)=><tr key={p.id}><td>{all.findIndex(other=>other.points===p.points)+1}</td><td>{p.name}</td><td>{p.played}</td><td>{p.points}</td></tr>)}</tbody></table></div>{!data!.standings.length&&<p>No players yet. Followers can join the roster above.</p>}<p className="form-hint">Hosts enter points using the league’s scoring rules. Equal points share a rank.</p>
 {showEvent&&managing&&<form key={editing?.id||'new-event'} className="post-form league-event" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const date=new Date(String(f.get('starts')));if(!Number.isFinite(date.getTime())){setError('Choose a valid game time.');return}act({action:'saveEvent',leagueId:league.id,eventId:editing?.id,name:String(f.get('name')),starts:date.toISOString(),details:String(f.get('details')),status:String(f.get('status'))},()=>{setEditing(null);setShowEvent(false)})}}><h3>{editing?'Edit game':'Schedule game'}</h3><label className="field">Game name<input name="name" required minLength={2} maxLength={100} defaultValue={editing?.name}/></label><label className="field">Start time (your local time)<input name="starts" type="datetime-local" required defaultValue={editing?localDate(editing.starts):''}/></label><label className="field">Details<textarea name="details" maxLength={2000} rows={3} defaultValue={editing?.details} placeholder="Where to play, club details, and how to join the game."/></label><label className="field">Status<select name="status" defaultValue={editing?.status||'scheduled'}><option value="scheduled">Scheduled</option><option value="completed">Completed · Include results in standings</option><option value="cancelled">Cancelled · Exclude results from standings</option></select></label><div className="room-actions"><button className="primary" disabled={busy}>Save game</button><button type="button" className="outline" onClick={()=>setShowEvent(false)}>Cancel</button></div></form>}
 <h3>Game schedule and results</h3>{data!.events.length===0&&<p className="muted">No games scheduled yet.</p>}{data!.events.map(event=><article className="league-event" key={event.id}><div className="room-heading"><h3>{event.name}</h3><span className="room-tag">{event.status}</span></div><p>{new Date(event.starts).toLocaleString(undefined,{dateStyle:'full',timeStyle:'short'})}</p><p className="community-body">{event.details}</p>{managing&&<button className="outline" disabled={busy} onClick={()=>{setEditing(event);setShowEvent(true)}}>Edit game / status</button>}
 {!!data!.results.filter(r=>r.eventId===event.id).length&&<div className="league-table-wrap"><table className="league-table"><caption>{event.status==='completed'?'Results':'Results · Not counted in standings'}</caption><thead><tr><th>Place</th><th>Player</th><th>Points</th>{managing&&<th>Manage</th>}</tr></thead><tbody>{data!.results.filter(r=>r.eventId===event.id).map(r=><tr key={r.userId}><td>{r.place}</td><td>{r.name}</td><td>{r.points}</td>{managing&&<td><button className="text-link" disabled={busy} onClick={()=>{if(window.confirm('Remove this result?'))act({action:'removeResult',leagueId:league.id,eventId:event.id,userId:r.userId})}}>Remove</button></td>}</tr>)}</tbody></table></div>}
 {managing&&event.status!=='cancelled'&&!!data!.standings.length&&<form className="post-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act({action:'result',leagueId:league.id,eventId:event.id,userId:String(f.get('player')),place:Number(f.get('place')),points:Number(f.get('points'))})}}><h4>Record or correct a result</h4><label className="field">Player<select name="player" required>{data!.standings.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="league-form-grid"><label className="field">Place<input name="place" type="number" required min={1} max={100000} step={1}/></label><label className="field">Points<input name="points" type="number" required min={0} max={1000000} step="0.01"/></label></div><p className="form-hint">Saving replaces this player’s result for this game. Mark the game Completed to count its points.</p><button className="outline" disabled={busy}>Save result</button></form>}</article>)}</>}
 </section>;
}
