'use client';
import {useEffect,useRef,useState} from 'react';
import {communityRequest} from './community-client';
import './community.css';
type Entry={id:string;userId:string;name:string;body:string;created:string;canRemove:boolean};
type Feed={posts:(Entry&{comments:number})[];nextBefore:string|null};
type Comments={comments:Entry[];nextBefore:string|null};
function CommentThread({roomId,postId,canPost,onCountChange}:{roomId:string;postId:string;canPost:boolean;onCountChange:(change:number)=>void}){
 const [data,setData]=useState<Comments|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);const lock=useRef(false);
 useEffect(()=>{const c=new AbortController();communityRequest<Comments>({roomId,postId},undefined,c.signal).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[roomId,postId,revision]);
 async function act(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 return <section className="community-comments" aria-label="Comments">{error&&<p className="error" role="alert">{error}</p>}{canPost&&<form className="post-form" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;act(async()=>{await communityRequest({}, {action:'comment',roomId,postId,body:String(new FormData(f).get('body'))});f.reset();onCountChange(1);setRevision(v=>v+1)})}}><label className="field">Add a comment<textarea name="body" required maxLength={2000} rows={2}/></label><button className="outline" disabled={busy}>Post comment</button></form>}
 {data?.comments.map(c=><article key={c.id}><div className="room-heading"><a className="profile-name" href={'/?profile='+encodeURIComponent(c.userId)}>{c.name}</a>{c.canRemove&&<button className="text-link" disabled={busy} onClick={()=>{if(window.confirm('Remove this comment?'))act(async()=>{await communityRequest({}, {action:'removeComment',roomId,commentId:c.id});onCountChange(-1);setRevision(v=>v+1)})}}>Remove</button>}</div><p className="community-body">{c.body}</p><small>{new Date(c.created).toLocaleString()}</small></article>)}{data?.comments.length===0&&<p className="muted">No comments yet.</p>}{data?.nextBefore&&<button className="outline" disabled={busy} onClick={()=>act(async()=>{const more=await communityRequest<Comments>({roomId,postId,before:data.nextBefore!});setData({...more,comments:[...data.comments,...more.comments]})})}>Earlier comments</button>}</section>;
}
export default function RoomCommunity({roomId,canPost}:{roomId:string;canPost:boolean}){
 const [data,setData]=useState<Feed|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[expanded,setExpanded]=useState<string[]>([]);const lock=useRef(false);
 useEffect(()=>{const c=new AbortController();setError('');communityRequest<Feed>({roomId},undefined,c.signal).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[roomId,revision]);
 async function act(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 return <section className="community-section"><div className="room-heading"><div><span className="eyebrow">ROOM CONVERSATION</span><h2>At the table.</h2></div><button className="outline" disabled={busy} onClick={()=>setRevision(v=>v+1)}>Refresh</button></div>{error&&<p className="error" role="alert">{error}</p>}
 {canPost?<form className="panel post-form community-section" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;act(async()=>{await communityRequest({}, {action:'post',roomId,body:String(new FormData(f).get('body'))});f.reset();setRevision(v=>v+1)})}}><label className="field">Post to this room<textarea name="body" required maxLength={5000} rows={3} placeholder="Who's playing? Share a game update or start a conversation."/></label><p className="form-hint">Visible to signed-in members who can view this room.</p><button className="primary" disabled={busy}>Post to room</button></form>:<p className="panel community-section">Follow this room to post and comment.</p>}
 {!data&&!error&&<p role="status">Loading conversation…</p>}{data?.posts.length===0&&<div className="panel empty"><h3>Be the first to say hello.</h3><p>Room followers can start a conversation here.</p></div>}
 {data?.posts.map(p=><article className="panel community-section" key={p.id}><div className="room-heading"><div><a className="profile-name" href={'/?profile='+encodeURIComponent(p.userId)}>{p.name}</a><p className="room-caption">{new Date(p.created).toLocaleString()}</p></div>{p.canRemove&&<button className="text-link" disabled={busy} onClick={()=>{if(window.confirm('Remove this post and its comments?'))act(async()=>{await communityRequest({}, {action:'removePost',roomId,postId:p.id});setRevision(v=>v+1)})}}>Remove</button>}</div><p className="community-body">{p.body}</p><button className="text-link" aria-expanded={expanded.includes(p.id)} onClick={()=>setExpanded(old=>old.includes(p.id)?old.filter(id=>id!==p.id):[...old,p.id])}>Comments ({p.comments})</button>{expanded.includes(p.id)&&<CommentThread roomId={roomId} postId={p.id} canPost={canPost} onCountChange={change=>setData(old=>old?{...old,posts:old.posts.map(post=>post.id===p.id?{...post,comments:Math.max(0,post.comments+change)}:post)}:old)}/>}</article>)}
 {data?.nextBefore&&<button className="outline" disabled={busy} onClick={()=>act(async()=>{const more=await communityRequest<Feed>({roomId,before:data.nextBefore!});setData({...more,posts:[...data.posts,...more.posts]})})}>Earlier posts</button>}</section>;
}
