import type {Group,Post} from './types';
export const demoGroups:Group[]=[
 {id:'rail',name:'The Home Rail',description:'The people in your corner, wherever you play.',kind:'Friends & family',owner:'demo',members:6},
 {id:'study',name:'Off the Felt',description:'Good questions. Better decisions.',kind:'Study group',owner:'demo',members:4},
 {id:'backers',name:'The Backer Room',description:'A private place for your tournament updates.',kind:'Backers',owner:'demo',members:3}
];
export const demoPosts:Post[]=[
 {id:'update-1',groupId:'rail',userId:'demo',name:'Alex Morgan',kind:'update',body:'Bagged for Day 2! Finished the night with 184,000. A few tough spots, a couple of good folds, and plenty to come back with. Thanks for being on the rail. 🤝',created:'2026-09-25T00:10:00Z',tournament:{event:'Weekend Main Event · Day 1',chips:184000,bigBlind:3000,remaining:42,status:'Bagged'},likes:8,liked:false,comments:[{id:'c1',name:'Jamie R.',body:'Great bag! Get some rest. We’re here for Day 2.',created:'2026-09-25T00:15:00Z'}],votes:{Fold:0,Call:0,Raise:0}},
 {id:'hand-1',groupId:'rail',userId:'alex',name:'Alex Morgan',kind:'hand',body:'A spot from earlier today. Curious how everyone plays this turn.',created:'2026-09-24T23:32:00Z',hand:{game:'NL Hold’em',stakes:'$1 / $3 cash',position:'BTN',stack:'100 BB',hero:'Ah Qh',board:'Qs 9h 4c 7h',pot:'$120',action:'UTG opens to $12. Hero calls on the button; blinds fold. Flop: UTG bets $18, Hero calls. Turn: UTG bets $60 into $64.',question:'Top pair and the nut flush draw. Call or raise this turn?',result:'Hero called. River 2h. UTG checked, Hero bet $120 and got called.',revealed:false},likes:3,liked:false,comments:[],votes:{Fold:1,Call:7,Raise:4}},
 {id:'update-2',groupId:'rail',userId:'jamie',name:'Jamie Rivers',kind:'update',body:'Good luck to everyone playing this weekend. Drop your updates here so we can follow along. Your rail is ready. ♠',created:'2026-09-24T21:15:00Z',likes:5,liked:false,comments:[],votes:{Fold:0,Call:0,Raise:0}},
 {id:'hand-2',groupId:'study',userId:'demo',name:'Alex Morgan',kind:'hand',body:'Reviewing this completed hand from last night.',created:'2026-09-24T22:00:00Z',hand:{game:'NL Hold’em',stakes:'Tournament · 1k/2k',position:'CO',stack:'28 BB',hero:'As Jd',board:'Jh 8c 3s',pot:'8 BB',action:'Hero opens 2.2 BB in the cutoff. Big blind calls. Flop: BB checks, Hero bets 2.5 BB. BB raises to 8 BB.',question:'What’s your response to the check-raise?',result:'Hero called and evaluated the turn.',revealed:false},likes:2,liked:false,comments:[],votes:{Fold:2,Call:5,Raise:1}},
 {id:'backer-1',groupId:'backers',userId:'demo',name:'Alex Morgan',kind:'update',body:'Day 1 recap for the group: one entry, bagged 61 big blinds. Day 2 starts tomorrow. I’ll post again at the first break.',created:'2026-09-25T00:20:00Z',tournament:{event:'Weekend Main Event',chips:184000,bigBlind:3000,remaining:42,status:'Bagged'},likes:2,liked:false,comments:[],votes:{Fold:0,Call:0,Raise:0}}
];
