import {z} from 'zod';
export function validCards(hero:string,board:string){const h=hero.trim().split(/\s+/).filter(Boolean),b=board.trim().split(/\s+/).filter(Boolean),all=[...h,...b];return h.length===2&&[0,3,4,5].includes(b.length)&&all.every(c=>/^[2-9TJQKA][cdhs]$/i.test(c))&&new Set(all.map(c=>c.toLowerCase())).size===all.length;}
const optionalText=(max:number)=>z.string().trim().max(max).default('');
export const handSchema=z.object({game:z.literal('NL Hold’em').default('NL Hold’em'),stakes:optionalText(60),position:optionalText(10),stack:optionalText(30),hero:optionalText(8),board:optionalText(20),pot:optionalText(30),action:optionalText(5000),question:optionalText(500),result:optionalText(2000),revealed:z.boolean().default(false)}).refine(h=>{
 const hero=h.hero.split(/\s+/).filter(Boolean),board=h.board.split(/\s+/).filter(Boolean),all=[...hero,...board];
 return [0,2].includes(hero.length)&&[0,3,4,5].includes(board.length)&&all.every(c=>/^[2-9TJQKA][cdhs]$/i.test(c))&&new Set(all.map(c=>c.toLowerCase())).size===all.length;
},'Cards are optional. If entered, use two distinct hole cards and 3, 4, or 5 board cards, with no duplicates.');
export const tournamentSchema=z.object({event:optionalText(120),chips:z.number().int().min(0).max(1e12).optional(),bigBlind:z.number().min(.01).max(1e10).optional(),remaining:z.number().int().min(0).max(1e6).optional(),status:z.enum(['Playing','On break','Bagged','Cashed','Out']).default('Playing'),gameType:z.enum(['tournament','cash']).default('tournament')});
export const postSchema=z.object({groupId:z.string().min(1),kind:z.enum(['hand','update']),body:optionalText(5000),hand:handSchema.optional(),tournament:tournamentSchema.optional(),images:z.array(z.string().max(420000)).max(3).optional(),keepImages:z.array(z.number().int().min(0).max(2)).max(3).optional(),sessionId:z.string().max(100).optional(),startSession:z.enum(['tournament','cash']).optional(),mentions:z.array(z.string().max(100)).max(20).default([])}).refine(p=>!!p.body||!!p.images?.length||!!p.keepImages?.length||!!p.startSession||!!p.tournament&&(!!p.tournament.event||p.tournament.status!=='Playing'||p.tournament.chips!==undefined||p.tournament.bigBlind!==undefined||p.tournament.remaining!==undefined)||!!p.hand&&[p.hand.position,p.hand.stakes,p.hand.stack,p.hand.hero,p.hand.board,p.hand.pot,p.hand.action,p.hand.question,p.hand.result].some(Boolean),'Add any detail, a message, or a photo. No individual field is required.');
